services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:${VERSION}
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8090
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ${APP_PATH}/pb_data:/pb_data
      - ${APP_PATH}/pb_hooks:/pb_hooks
      - ${APP_PATH}/pb_migrations:/pb_migrations
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
